### ISSUE TITLE
Prepare for release - Update demo and guide

### ISSUE THREAD

**Issue by dan11003** [dan11003/tbv_slam_public#4]
We now have two versions of TBV

1. Which precomputes odometry and generates CorAl training data, and stores it into simple graph files.
2. Which computes odometry directly for fast processing of new bag files.

Add a new section in the readme on how to run TBV (version 2 in this issue). Include an evaluation of drift / ATE and ensure the numbers are consistent with the article.

**Comment by maxhilger** [comment]
Added documentation for parallel node and Docker
