### ISSUE TITLE
Prepare for release - Tweak performance of pose-graph optimization

### ISSUE THREAD

**Issue by dan11003** [dan11003/tbv_slam_public#5]
Ensure that optimization is running at a reasonable speed, at least  0.2-1Hz.

**Comment by maxhilger** [comment]
Tested on sequence 10-12-32 of Oxford. With the current settings, the PGO takes on average 115 ms, and a maximum of 825 ms. I could not observe significant differences with other settings. IMO, the current settings are sufficient.
