### ISSUE TITLE
Prepare for release - Update CFEAR-3

### ISSUE THREAD

**Issue by dan11003** [dan11003/tbv_slam_public#6]
CFEAR-3 is likely faster / more accurate in the released version compared to the RAL-V1 version. Pull [CFEAR-3 master branch](https://github.com/dan11003/CFEAR_Radarodometry_code_public)  into TBV.
Do this after the performance of TBV has been verified, to ensure that these updates do not introduce additional issues.

**Comment by maxhilger** [comment]
Merged released master into develop_tbv_release branch
